# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-09-17 14:45+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"Language: el\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.16.0\n"

#: geovisio/templates/main.html:45
msgid "Simple 360Â° geolocated pictures hosting"
msgstr ""

#: geovisio/templates/main.html:47
msgid "Full page version"
msgstr ""

#: geovisio/templates/main.html:51
msgid "Viewer"
msgstr ""

#: geovisio/templates/main.html:52
msgid "Embed pre-configured viewer"
msgstr ""

#: geovisio/templates/main.html:53
msgid "Easiest way to have a working GeoVisio viewer on your website"
msgstr ""

#: geovisio/templates/main.html:59
msgid "Use JS library"
msgstr ""

#: geovisio/templates/main.html:60
msgid "A completely configurable viewer for your website"
msgstr ""

#: geovisio/templates/main.html:82
msgid "Links"
msgstr ""

#: geovisio/templates/main.html:84
msgid "Pictures viewer"
msgstr ""

#: geovisio/templates/main.html:86
msgid "API docs"
msgstr ""

#: geovisio/templates/main.html:88
msgid "JS library docs"
msgstr ""

#: geovisio/templates/main.html:90
msgid "Repositories"
msgstr ""

#: geovisio/templates/viewer.html:22
msgid "You need to enable JavaScript to run this app."
msgstr ""

#: geovisio/utils/auth.py:201
msgid "Authentication is mandatory"
msgstr ""

#: geovisio/utils/auth.py:330
msgid "Only Bearer token are supported"
msgstr ""

#: geovisio/utils/excluded_areas.py:82
msgid "Impossible to find excluded area"
msgstr ""

#: geovisio/utils/pictures.py:305
#, python-format
msgid ""
"Invalid '%(format)s' format for image, only the following formats are "
"available: %(allowed_formats)s"
msgstr ""

#: geovisio/utils/pictures.py:419
msgid "Picture can't be found, you may check its ID"
msgstr ""

#: geovisio/utils/pictures.py:422
msgid "Picture is not available (either hidden by admin or processing)"
msgstr ""

#: geovisio/utils/pictures.py:430
msgid "HD Picture file is not available"
msgstr ""

#: geovisio/utils/pictures.py:449
msgid "Picture derivates file are not available"
msgstr ""

#: geovisio/utils/pictures.py:466 geovisio/web/pictures.py:55
#: geovisio/web/pictures.py:100 geovisio/web/pictures.py:210
msgid "Unable to read picture on filesystem"
msgstr ""

#: geovisio/utils/reports.py:142 geovisio/utils/upload_set.py:352
#: geovisio/web/params.py:359
msgid "Unsupported filter parameter"
msgstr ""

#: geovisio/utils/sequences.py:376
msgid ""
"Sort by file date is not possible on this sequence (no file date "
"information available on pictures)"
msgstr ""

#: geovisio/utils/sequences.py:395
#, python-format
msgid ""
"Sort using %(sort)s is not possible on this sequence, picture %(pic)s is "
"missing mandatory metadata"
msgstr ""

#: geovisio/utils/sequences.py:585 geovisio/web/collections.py:620
#, python-format
msgid "Collection %(c)s wasn't found in database"
msgstr ""

#: geovisio/utils/tokens.py:43
msgid "JWT token signature does not match"
msgstr ""

#: geovisio/utils/tokens.py:57
msgid "Token does not exist anymore"
msgstr ""

#: geovisio/utils/tokens.py:61
msgid ""
"Token not yet claimed, this token cannot be used yet. Either claim this "
"token or generate a new one"
msgstr ""

#: geovisio/utils/upload_set.py:158
msgid ""
"The picture is too similar to another one (nearby and taken almost at the"
" same time)"
msgstr ""

#: geovisio/utils/upload_set.py:161
msgid "The sent file is not a valid JPEG"
msgstr ""

#: geovisio/utils/upload_set.py:164
msgid "The picture has invalid EXIF or XMP metadata, making it impossible to use"
msgstr ""

#: geovisio/utils/upload_set.py:167
msgid "Something went very wrong, but not due to the picture itself"
msgstr ""

#: geovisio/web/auth.py:61
msgid "Impossible to finish authentication flow"
msgstr ""

#: geovisio/web/auth.py:65
msgid ""
"You can try to clear your cookies and retry. If the problem persists, "
"contact your instance administrator."
msgstr ""

#: geovisio/web/collections.py:291
#, python-format
msgid "There is no collection created after %(d)s"
msgstr ""

#: geovisio/web/collections.py:293
#, python-format
msgid "There is no collection created before %(d)s"
msgstr ""

#: geovisio/web/collections.py:401 geovisio/web/items.py:393
msgid "Collection doesn't exist"
msgstr ""

#: geovisio/web/collections.py:460
msgid "Impossible to find a thumbnail for the collection"
msgstr ""

#: geovisio/web/collections.py:580 geovisio/web/items.py:1170
msgid ""
"Picture visibility parameter (visible) should be either unset, true or "
"false"
msgstr ""

#: geovisio/web/collections.py:586
msgid ""
"Sequence title is not valid, should be a string with a max of 250 "
"characters"
msgstr ""

#: geovisio/web/collections.py:592
msgid "Sort order parameter is invalid"
msgstr ""

#: geovisio/web/collections.py:603
msgid ""
"Relative heading is not valid, should be an integer in degrees from -180 "
"to 180"
msgstr ""

#: geovisio/web/collections.py:624
msgid "You're not authorized to edit this sequence"
msgstr ""

#: geovisio/web/collections.py:633
#, python-format
msgid "Sequence %(c)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""

#: geovisio/web/collections.py:768
msgid "Sequence doesn't exists"
msgstr ""

#: geovisio/web/collections.py:913 geovisio/web/stac.py:349
#, python-format
msgid "Impossible to find user %(u)s"
msgstr ""

#: geovisio/web/collections.py:944 geovisio/web/stac.py:359
#, python-format
msgid "No data loaded for user %(u)s"
msgstr ""

#: geovisio/web/collections.py:946
msgid "No matching sequences found"
msgstr ""

#: geovisio/web/excluded_areas.py:134
msgid "You must be logged-in as admin to access all excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:136
msgid "You're not authorized to access all excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:173 geovisio/web/excluded_areas.py:183
#: geovisio/web/excluded_areas.py:337 geovisio/web/excluded_areas.py:344
msgid "Impossible to create an Excluded Area"
msgstr ""

#: geovisio/web/excluded_areas.py:175 geovisio/web/excluded_areas.py:339
msgid "Parameter for creating an Excluded Area should be a valid JSON"
msgstr ""

#: geovisio/web/excluded_areas.py:178 geovisio/web/excluded_areas.py:236
msgid "You must be logged-in as admin to edit excluded areas"
msgstr ""

#: geovisio/web/excluded_areas.py:231 geovisio/web/excluded_areas.py:243
msgid "Impossible to replace all Excluded Areas"
msgstr ""

#: geovisio/web/excluded_areas.py:233
msgid "Parameter for replacing all Excluded Areas should be a valid JSON"
msgstr ""

#: geovisio/web/excluded_areas.py:273
msgid "You must be logged-in as admin to delete excluded areas"
msgstr ""

#: geovisio/web/items.py:356
msgid "limit parameter should be an integer between 1 and 10000"
msgstr ""

#: geovisio/web/items.py:358
msgid "limit parameter should be a valid, positive integer (between 1 and 10000)"
msgstr ""

#: geovisio/web/items.py:363
msgid "`startAfterRank` and `withPicture` are mutually exclusive parameters"
msgstr ""

#: geovisio/web/items.py:370
msgid "startAfterRank parameter should be a positive integer (starting from 1)"
msgstr ""

#: geovisio/web/items.py:372
msgid "startAfterRank parameter should be a valid, positive integer"
msgstr ""

#: geovisio/web/items.py:399
#, python-format
msgid "No more items in this collection (last available rank is %(r)s)"
msgstr ""

#: geovisio/web/items.py:409
#, python-format
msgid "Picture with id %(p)s does not exist"
msgstr ""

#: geovisio/web/items.py:695
msgid "Item doesn't exist"
msgstr ""

#: geovisio/web/items.py:754
msgid "Search using POST method should have a JSON body"
msgstr ""

#: geovisio/web/items.py:763
msgid "Parameter limit must be either empty or a number between 1 and 10000"
msgstr ""

#: geovisio/web/items.py:819
msgid ""
"Parameter place_fov_tolerance must be either empty or a number between 2 "
"and 180"
msgstr ""

#: geovisio/web/items.py:841
msgid ""
"Parameter intersects should contain a valid GeoJSON Geometry (not a "
"Feature)"
msgstr ""

#: geovisio/web/items.py:857
msgid "Parameter ids should be a JSON array of strings"
msgstr ""

#: geovisio/web/items.py:869
msgid "Parameter collections should be a JSON array of strings"
msgstr ""

#: geovisio/web/items.py:880
msgid "Picture doesn't exist"
msgstr ""

#: geovisio/web/items.py:983 geovisio/web/upload_set.py:527
msgid "Content type should be multipart/form-data"
msgstr ""

#: geovisio/web/items.py:987
msgid "Missing \"position\" parameter"
msgstr ""

#: geovisio/web/items.py:994
msgid "Position in sequence should be a positive integer"
msgstr ""

#: geovisio/web/items.py:1008 geovisio/web/upload_set.py:336
msgid ""
"Longitude cannot be overridden alone, override_latitude also needs to be "
"set"
msgstr ""

#: geovisio/web/items.py:1010 geovisio/web/upload_set.py:338
msgid ""
"Latitude cannot be overridden alone, override_longitude also needs to be "
"set"
msgstr ""

#: geovisio/web/items.py:1011 geovisio/web/upload_set.py:311
#, python-format
msgid "For parameter `override_longitude`, `%(v)s` is not a valid longitude"
msgstr ""

#: geovisio/web/items.py:1012 geovisio/web/upload_set.py:316
#, python-format
msgid "For parameter `override_latitude`, `%(v)s` is not a valid latitude"
msgstr ""

#: geovisio/web/items.py:1031
msgid "Picture blur status should be either unset, true or false"
msgstr ""

#: geovisio/web/items.py:1035
msgid "No picture file was sent"
msgstr ""

#: geovisio/web/items.py:1041 geovisio/web/upload_set.py:377
msgid "Picture file is either missing or in an unsupported format (should be jpg)"
msgstr ""

#: geovisio/web/items.py:1048
#, python-format
msgid "Collection %(s)s wasn't found in database"
msgstr ""

#: geovisio/web/items.py:1052
msgid "You're not authorized to add picture to this collection"
msgstr ""

#: geovisio/web/items.py:1057
msgid "The collection has been deleted, impossible to add pictures to it"
msgstr ""

#: geovisio/web/items.py:1087
msgid "Picture at given position already exist"
msgstr ""

#: geovisio/web/items.py:1089 geovisio/web/upload_set.py:615
msgid "Impossible to parse picture metadata"
msgstr ""

#: geovisio/web/items.py:1091 geovisio/web/upload_set.py:622
msgid "Picture has invalid metadata"
msgstr ""

#: geovisio/web/items.py:1099 geovisio/web/upload_set.py:648
msgid "Picture wasn't correctly saved in filesystem"
msgstr ""

#: geovisio/web/items.py:1182
msgid ""
"Heading is not valid, should be an integer in degrees from 0Â° to 360Â°. "
"North is 0Â°, East = 90Â°, South = 180Â° and West = 270Â°."
msgstr ""

#: geovisio/web/items.py:1199 geovisio/web/items.py:1290
#, python-format
msgid "Picture %(p)s wasn't found in database"
msgstr ""

#: geovisio/web/items.py:1203 geovisio/web/items.py:1294
msgid "You're not authorized to edit this picture"
msgstr ""

#: geovisio/web/items.py:1213
#, python-format
msgid "Picture %(p)s is in %(s)s state, its visibility can't be changed for now"
msgstr ""

#: geovisio/web/map.py:124
msgid "One of required parameter is empty"
msgstr ""

#: geovisio/web/map.py:126
msgid "Tile format is invalid, should be either pbf or mvt"
msgstr ""

#: geovisio/web/map.py:130 geovisio/web/map.py:132
msgid "X or Y parameter is out of bounds"
msgstr ""

#: geovisio/web/map.py:134
msgid "Z parameter is out of bounds (should be 0-15)"
msgstr ""

#: geovisio/web/map.py:145
msgid "Impossible to get tile"
msgstr ""

#: geovisio/web/params.py:101
msgid "Parameter datetime should contain one or two dates"
msgstr ""

#: geovisio/web/params.py:171
msgid ""
"Parameter bbox must contain valid longitude (-180 to 180) and latitude "
"(-90 to 90) values"
msgstr ""

#: geovisio/web/params.py:176
msgid "Parameter bbox must be in format [minX, minY, maxX, maxY]"
msgstr ""

#: geovisio/web/params.py:213
#, python-format
msgid "Parameter %(p)s must be coordinates in lat,lon format"
msgstr ""

#: geovisio/web/params.py:216
#, python-format
msgid "Longitude in parameter %(p)s is not valid (should be between -180 and 180)"
msgstr ""

#: geovisio/web/params.py:217
#, python-format
msgid "Latitude in parameter %(p)s is not valid (should be between -90 and 90)"
msgstr ""

#: geovisio/web/params.py:240 geovisio/web/params.py:253
#, python-format
msgid ""
"Parameter %(p)s is invalid (should be a distance range in meters like "
"\"5-15\")"
msgstr ""

#: geovisio/web/params.py:246
#, python-format
msgid "Parameter %(p)s has a min value greater than its max value"
msgstr ""

#: geovisio/web/params.py:320
#, python-format
msgid "Parameter %(p)s must be a valid list"
msgstr ""

#: geovisio/web/params.py:444
msgid "Unsupported sortby parameter: invalid column name"
msgstr ""

#: geovisio/web/params.py:452
msgid "Unsupported sortby parameter: syntax isn't correct"
msgstr ""

#: geovisio/web/params.py:478
#, python-format
msgid "limit parameter should be a valid, positive integer (between 1 and %(v)s)"
msgstr ""

#: geovisio/web/params.py:481
#, python-format
msgid "limit parameter should be an integer between 1 and %(v)s"
msgstr ""

#: geovisio/web/params.py:492
msgid "longitude needs to be between -180 and 180"
msgstr ""

#: geovisio/web/params.py:502
msgid "latitude needs to be between -90 and 90"
msgstr ""

#: geovisio/web/pictures.py:189
msgid "Tiles are not available for flat pictures"
msgstr ""

#: geovisio/web/pictures.py:194
msgid "Column parameter is invalid, should be an integer"
msgstr ""

#: geovisio/web/pictures.py:197
msgid "Column parameter is invalid"
msgstr ""

#: geovisio/web/pictures.py:202
msgid "Row parameter is invalid, should be an integer"
msgstr ""

#: geovisio/web/pictures.py:205
msgid "Row parameter is invalid"
msgstr ""

#: geovisio/web/reports.py:89 geovisio/web/reports.py:99
msgid "Impossible to create a Report"
msgstr ""

#: geovisio/web/reports.py:91
msgid "Parameter for creating a Report should be a valid JSON"
msgstr ""

#: geovisio/web/reports.py:144
msgid "Only authenticated users can access reports"
msgstr ""

#: geovisio/web/reports.py:148 geovisio/web/reports.py:266
msgid "Report doesn't exist"
msgstr ""

#: geovisio/web/reports.py:157
msgid "You're not authorized to access this report"
msgstr ""

#: geovisio/web/reports.py:277
msgid "You're not authorized to edit this Report"
msgstr ""

#: geovisio/web/reports.py:284
msgid "Impossible to edit the Report"
msgstr ""

#: geovisio/web/reports.py:286
msgid "Parameter for editing the Report should be a valid JSON"
msgstr ""

#: geovisio/web/reports.py:349 geovisio/web/reports.py:392
#: geovisio/web/upload_set.py:265 geovisio/web/upload_set.py:385
msgid "Impossible to parse parameters"
msgstr ""

#: geovisio/web/reports.py:352
msgid "You're not authorized to list reports"
msgstr ""

#: geovisio/web/rss.py:22
#, python-format
msgid "Sequence \"%(name)s\" by \"%(user)s\" was captured on %(date)s."
msgstr ""

#: geovisio/web/rss.py:49
msgid "GeoVisio collections"
msgstr ""

#: geovisio/web/rss.py:51
msgid "List of collections from this GeoVisio server"
msgstr ""

#: geovisio/web/tokens.py:101 geovisio/web/tokens.py:144
#: geovisio/web/tokens.py:232
msgid "Impossible to find token"
msgstr ""

#: geovisio/web/tokens.py:182
msgid "Impossible to generate a new token"
msgstr ""

#: geovisio/web/tokens.py:237
msgid "Token already claimed by another account"
msgstr ""

#: geovisio/web/upload_set.py:133
msgid "Impossible to create an UploadSet"
msgstr ""

#: geovisio/web/upload_set.py:135
msgid "Parameter for creating an UploadSet should be a valid JSON"
msgstr ""

#: geovisio/web/upload_set.py:181 geovisio/web/upload_set.py:214
#: geovisio/web/upload_set.py:726
msgid "UploadSet doesn't exist"
msgstr ""

#: geovisio/web/upload_set.py:216
msgid "You're not authorized to list pictures in this upload set"
msgstr ""

#: geovisio/web/upload_set.py:303
msgid ""
"Parameter `override_capture_time` is not a valid datetime, it should be "
"an iso formated datetime (like '2017-07-21T17:32:28Z')."
msgstr ""

#: geovisio/web/upload_set.py:370
msgid "No file was sent"
msgstr ""

#: geovisio/web/upload_set.py:536 geovisio/web/upload_set.py:712
#, python-format
msgid "UploadSet %(u)s does not exist"
msgstr ""

#: geovisio/web/upload_set.py:540
msgid "You're not authorized to add picture to this upload set"
msgstr ""

#: geovisio/web/upload_set.py:580
msgid "The item has already been added to this upload set"
msgstr ""

#: geovisio/web/upload_set.py:587
msgid "The same picture has already been sent in a past upload"
msgstr ""

#: geovisio/web/upload_set.py:630
msgid "Impossible to open file as image. The only supported image format is jpg."
msgstr ""

#: geovisio/web/upload_set.py:716
msgid "You're not authorized to complete this upload set"
msgstr ""

#: geovisio/web/upload_set.py:763
msgid "You're not authorized to delete this upload set"
msgstr ""

#: geovisio/web/users.py:82
msgid "Impossible to find user"
msgstr ""

#: geovisio/web/users.py:158
msgid ""
"No search parameter given, you should provide `q=<pattern>` as query "
"parameter"
msgstr ""

#: geovisio/web/utils.py:55
msgid "No default account defined, please contact your instance administrator"
msgstr ""
